#
# See https://docs.microsoft.com/azure/devops/pipelines/yaml-schema for reference.
#

variables:
- name: Build.Repository.Clean
  value: true
- name: _TeamName
  value: AspNetCore
- name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
  value: true
- name: _InternalRuntimeDownloadArgs
  value: ''

trigger:
  branches:
    include:
      - master

stages:
- stage: build
  displayName: Build
  jobs:
  - template: /eng/common/templates/jobs/jobs.yml
    parameters:
      helixRepo: dotnet/aspnetcore-tooling
      helixType: build.product/
      enablRichCodeNavigation: true
      jobs:
      - job: Windows
        pool:
          name: NetCorePublic-Pool
          queue: buildpool.windows.10.amd64.vs2019.pre.open
        variables:
        - _BuildArgs: ''

        steps:
        - task: NodeTool@0
          displayName: Install Node 10.x
          inputs:
            versionSpec: 10.x
        - powershell: npm install -g yarn
          displayName: Install yarn
          condition: succeeded()
        - task: NuGetCommand@2
          displayName: 'Clear NuGet caches'
          condition: succeeded()
          inputs:
            command: custom
            arguments: 'locals all -clear'

        - script: eng\common\cibuild.cmd
            -configuration $(_BuildConfig)
            -msbuildEngine dotnet
            -prepareMachine
            $(_BuildArgs)
            $(_InternalRuntimeDownloadArgs)
          name: Build
          displayName: Build
          condition: succeeded()
